# Generated by Django 4.2.2 on 2024-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "__first__"),
        ("student", "0002_alter_academicinfo_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=206697, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="enrolledstudent",
            unique_together={("class_name", "roll")},
        ),
        migrations.RemoveField(
            model_name="enrolledstudent",
            name="session_year",
        ),
    ]
