# Generated by Django 4.2.2 on 2024-10-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "__first__"),
        ("student", "0003_alter_academicinfo_registration_no_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrolledstudent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrolledstudent",
            name="session_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.session",
            ),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=847590, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="enrolledstudent",
            unique_together={("class_name", "session_year", "roll")},
        ),
    ]
